# Generated by Django 4.2.7 on 2024-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_price', models.FloatField()),
                ('item_rating', models.IntegerField(blank=True)),
                ('item_reviews', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
