# Generated by Django 4.2.7 on 2024-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotAmazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_age', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('is_admin', models.BooleanField(verbose_name=False)),
                ('username', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_first', models.CharField(max_length=100)),
                ('user_last', models.CharField(max_length=100)),
            ],
        ),
    ]
